### ISSUE TITLE
Cell not Updating in Java

### ISSUE THREAD

**Issue by FLUXparticle** [SodiumFRP/sodium#101]
Hi,

I found a behavior that I would call a bug. If I combine two Cells with a lift, changes of the left one are not reflected as long the right one hold the value null. If the left one hold the value null, changes of the right one are reflected. This is due to the apply method in Cell where a lambda from the left cell is applied to the right one. If the right value is null, it is not applied.

**Comment by the-real-blackh** [comment]
As a functional programmer, I never even think of using null, but it should work all the same. Thanks!

**Comment by the-real-blackh** [comment]
This should be fixed now. Please re-open if it doesn't work.
