### ISSUE TITLE
Educational port

### ISSUE THREAD

**Issue by BartAdv** [SodiumFRP/sodium#103]
Hopefully it is okay to ask question in an issue, I was wondering what would be the best place and I noticed there are some issues concerning ports here, so I decided to give it a go.

I thought about starting a port for the sake of gaining better understanding, not really aiming to get something that can be on par with Java version (which is most likely just very hard task). My language of choice would be Idris, not because of its dependently typed nature (I don't think it would be of any use in this case), but just because it's a nice language with tiny ecosystem, so if anything good would came out of this, then at least it would gain some useful FRP library (and if not, then at least apart from educational aspect, some test-drive to Idris features can be achieved (if there is something needed like weak references etc.)).

However, I'm not sure what should be the reference implementation for such endeavour. Syntactically, Idris is close to Haskell, but it's strict, so there are most likely more differencies than similarities (although it supports laziness). On top of that, haskell implementation is currently abandoned (although maybe this means it may be non-optimal, but simple to follow-along?).

What are your thoughts on that?

**Comment by Ziriax** [comment]
[The Sodium FRP forum](http://sodium.nz) might be a better place to ask this?

**Comment by BartAdv** [comment]
Oh, right!
