### ISSUE TITLE
Can you tell me the F# version status?

### ISSUE THREAD

**Issue by the-real-blackh** [SodiumFRP/sodium#111]
Hi @jam40jeff, someone is asking what the status of the F# version is:

http://sodium.nz/t/what-is-the-f-version-status/186

Thank you!

**Comment by jam40jeff** [comment]
The F# version currently is usable and has feature parity with the Java version (which is equivalent to the C# 1.0 version).

However, I consider the C# 2.0 version to be the most "complete" version of Sodium, with performance upgrades, improved memory management, and the addition of DiscreteCell<T>.  F# still needs to be upgraded to have feature parity with the C# 2.0 version.

**Comment by lust4life** [comment]
thanks, will check the c# 2.0 version

**Comment by jam40jeff** [comment]
F# will be updated to match the 3.0 C# release soon.

**Comment by jam40jeff** [comment]
Will be implemented by #146.
