### ISSUE TITLE
typo in method ```Stream<A> orElse(Iterable<Stream<A>> ss)```?

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/sodium#112]
In the Java version
I suspect that:
```
    public static <A> Stream<A> orElse(Iterable<Stream<A>> ss) {
        return Stream.<A>merge(ss, new Lambda2<A,A,A>() {
            public A apply(A left, A right) { return right; }
        });
    }
```
in Stream.java, Should be:
```
    public static <A> Stream<A> orElse(Iterable<Stream<A>> ss) {
        return Stream.<A>merge(ss, new Lambda2<A,A,A>() {
            public A apply(A left, A right) { return left; }
        });
    }
```
(swap ```return right;``` with ```return left;```)

**Comment by jam40jeff** [comment]
Yes, that is correct.  It looks like a bug.  I checked the C# code and it does in fact return left.

**Comment by jam40jeff** [comment]
Actually, I just took a look at the Java code, and it is correct.  Are you sure you have updated to the latest version?

**Comment by jam40jeff** [comment]
Sorry for the confusion, I was looking at the wrong method in the Java code.  The one that operates on a collection of streams is in fact incorrect.  I will fix it.

**Comment by the-real-blackh** [comment]
@clinuxrulz thank you for finding and reporting this! @jam40jeff thank you for fixing. This is important so I'll make a new release soon.
