### ISSUE TITLE
PCL supporting nuget

### ISSUE THREAD

**Issue by Confuset** [SodiumFRP/sodium#114]
hey is it possible to release a version of SodiumFRP that supports PCL? i want to use it with Xamarin.Forms but this seems to work only with PCL.

I asked the guys from priority queue to also support PCL and they did it :-)
https://github.com/BlueRaja/High-Speed-Priority-Queue-for-C-Sharp/issues/18

so far you only have to add a new project (Xamarin library/PCL), add all files as references (so you dont have them twice) and install/update priority queue. That is basically it…
iam not that familiar with nuget, otherwise i would create a pull request for this. but since the steps are pretty simple i think this is ok…

what do you think?

**Comment by jam40jeff** [comment]
Would supporting NetStandard 2.0 do the trick?  I think Microsoft is
deprecating PCLs in favor of NetStandard.

**Comment by Confuset** [comment]
I think so too. Just tried it, and the funny thing is that older uwp/uap do not support .NetStandard. android and iPhone work without any problems.

Also you will not be able to properly reference High Speed Priority Queue as this does not support .NetStandard…

**Comment by Confuset** [comment]
but i think i can workaround. i just added sodium as submodule into my project and that seems to work like a charm :-)

**Comment by BlueRaja** [comment]
> Also you will not be able to properly reference High Speed Priority Queue as this does not support .NetStandard…

Actually, it does!  I added support for legacy .Net 2.0, .Net 4.0, PCL, and UWP, as well as the new .Net Standard 1.0 _(which is forward-compatible with .Net Standard 2.0)_

**Comment by jam40jeff** [comment]
Awesome!  I was going to look into this more myself, but thanks for saving
me the time, BlueRaja.  Also, thank you for providing a great library for
us to leverage.

It looks like supporting .NET Standard 1.0 is the way to go, as that would
mean we would be providing support for the largest number of platforms.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by Confuset** [comment]
ha. that was my mistake..i did not think about using older .netstandard :-( stupid me

keep in mind though that you are using System.Threads which can be problematic/not supported befor .Net Standard 2.0
https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.0_ref.md

https://github.com/dotnet/standard/tree/master/docs/versions
https://raw.githubusercontent.com/dotnet/standard/master/docs/versions/netstandard2.0_diff.md
search for class Thread

**Comment by Confuset** [comment]
Or take a look here
https://apisof.net/catalog/System.Threading.Thread

**Comment by Confuset** [comment]
Just created a pull request for  .Net Standard 1.1
#119

**Comment by jam40jeff** [comment]
This will be covered by #121.
