### ISSUE TITLE
Cell updates listener: is this expected behaviour?

### ISSUE THREAD

**Issue by spockoyno** [SodiumFRP/sodium#115]
The following Scala code  (for a subclass of scalafx Label) works fine with GUI:

class LabelRx(val data: Cell[String]) extends Label(" ") {
private val listen = data.updates().listen((t: String) => text = t) }

However,  the statement

  data.updates().listen((t: String) => text = t)

(without assignment) produces an unresponsive  label. 
Is this a bug? Or is it expected behaviour?

**Comment by clinuxrulz** [comment]
I had a quick peak at the Scala code. It seems that ```listen``` in the Scala version is the same as ```listenWeak``` in the Java version. I've never used the Scala version, but I though all versions made to work the same way. (```listen``` in scala did not place the listener into a global keep alive list)

**Comment by spockoyno** [comment]
That's a very useful clarification. Thank you!

**Comment by the-real-blackh** [comment]
@clinuxrulz During the writing of the book, after careful consideration, I changed to the way it is now in the Java version. The Scala version hasn't received much maintenance so it's out of date. There are quite a few issues like this.

**Comment by clinuxrulz** [comment]
@the-real-blackh that sounds OK. Better to have a leak, than unexpected behaviour. The end user can always go back to fix theirs leaks. (Remembering to unlisten.)

**Comment by spockoyno** [comment]
@the-real-blackh Indeed it seems like there're quite a few differences between the Scala and Java versions. So I'm writing a Scala wrapper around the Java library instead. 

A small question:  The method in the Cell.java
   final Stream<A> updates(Transaction trans) {   return str;  }
is independent from the Transaction. Does this have some significance (or is just for compatibility)?

PS Huge thanks for the excellent framework and book!

**Comment by the-real-blackh** [comment]
@spockoyno It would be great to get whatever you've done checked in.

That transaction is left over from an older way of doing things. I just checked in a change to take it out.

**Comment by spockoyno** [comment]
I'd be happy to. Provided it's decent quality stuff, still early days.

**Comment by jam40jeff** [comment]
Closing as I don't believe this is an issue anymore after the rework of the Scala version.
