### ISSUE TITLE
Feature Request: listenWeak for Cell in Java version.

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/sodium#117]
I'm aware of the ```removeNotify()``` trick used in SWidgets.

However when a gui component is removed from its parent, it does not always mean that it is no longer used. Some gui components can switch to a different parent, still triggering the ```removeNotify()``` midway.

So the end-user can have their own keepAlive list in their UI class, and use weak listeners instead to work around the problem. Just would be handy to have a listenWeak on Cell to cut down on key-strokes.

**Comment by the-real-blackh** [comment]
That sounds reasonable. I'll implement it some time. Feel free to do it yourself.
