### ISSUE TITLE
Fix netstandard support

### ISSUE THREAD

**Issue by jam40jeff** [SodiumFRP/sodium#121]
I am rolling back the support for netstandard 1.1.  The main reason is that the implementation using Tasks causes severe performance problems over having a single dedicated thread.

Also, we need to rework the single Sodium project to have multiple targets instead of separate projects.  Multiple targets should be included in the output NuGet package as well.

There are a couple ways we can move forward once the project is configured correctly.  We could use conditionals to try and support both .NET 4.5 as well as netstandard 1.1 with different code (use `Thread` for 4.5 and `Task` with `TaskCreationOptions.LongRunning` for netstandard 1.1.)  Or we could instead support netstandard 2.0 and just use `Thread` as this is now supported.

**Comment by jam40jeff** [comment]
@Confuset If you still need netstandard 1.1 for the time being, please migrate the project you added out into a fork for your own usage until we can properly support this.  Thanks!

**Comment by jam40jeff** [comment]
The reason for the performance issues is that the `AsyncBlockingCollection` was executing the cleanup code on the finalizer thread.  This was due to the fact that the `AsyncManualReset.Set` method was being called from the stream destructor (`~Stream`) and synchronously signalling the collection.  An alternative which would work for netstandard 1.1 would be to go back to the method in the first attempt, where the `Task` was started on a new thread, but then ran synchronously after that.  However, there are two main disadvantages to this method which are why I'd like to use proper `Thread`s for .NET 4.5 and netstandard 2.0 support:

(1) Two threads from the thread pool will always be used up.
(2) The behavior of `TaskCreationOptions.LongRunning` is currently that it starts a new thread, but this is undocumented and could change at any time.

**Comment by Confuset** [comment]
Thanks for the headsup.
I do not really Need 1.1 but I thought to go as low as possible with.

I don't know if using a proper Thread vs. a Long running thread-pool thread really makes a big difference ressource wise.
It would also be possible to merge those two threads into one and only use one thread for all the cleanup stuff.

Also the more I think about it, why not use something that does refcounting or figure out different styles of cleaning up. The more I think about it, the more it feels like we are rebuilding the garbagecollector here.

Do you have a simple example which demonstrates why this code is needed? Maybe I can figure out something different.

**Comment by jam40jeff** [comment]
> I don't know if using a proper Thread vs. a Long running thread-pool thread really makes a big difference ressource wise.

There are a couple things to consider here:
(1) The way we wrote it (which is my fault because I'm the one who suggested it) to use the async blocking collection was problematic because the continuations were executed on the finalizer thread.  One of the main purposes of this is to do cleanup work on another thread other than the finalizer thread.
(2) If the code is reverted to what you first submitted, *currently* it will behave as desired (other than permanently occupying a thread-pool thread), with the task created with `TaskCreationOptions.LongRunning` executing on a new thread grabbed from the thread pool.  However, the fact that `TaskCreationOptions.LongRunning` is an undocumented implementation detail and could change in future versions of the framework.

If we do wish to support netstandard1.1, we could go back to your original commit, and then use a conditional compilation symbol to switch the implementation between that and the more proper `Thread` implementation for build targets that support threads.

**Comment by jam40jeff** [comment]
> Also the more I think about it, why not use something that does refcounting or figure out different styles of cleaning up. The more I think about it, the more it feels like we are rebuilding the garbagecollector here.

Implementing refcounting (as the TypeScript implementation does) would be a huge step backwards.  It puts more responsibility on the developer to manually declare things like which streams may be returned within an FRP primitive (such as Map or Switch).  This can easily lead to memory leaks.  Basically, refcounting *is* an attempt at building a replacement for garbage collection and should only be done if a garbage collector is not available.

What we are doing is "empowering" the finalizer.  In Java, this is not as important as you have some guarantees that are not in C# (albeit with a performance penalty).  We are utilizing garbage collection to let us know when streams are no longer able to be used, and then cleaning up other FRP graph information related to those streams.  In Java, this cleanup is done directly in the `finalize` method due to the guarantees the Java runtime provides about order of finalization.  However, in C#, objects referenced by an object being garbage collected may have already been garbage collected themselves, which means you can only utilize value types or unmanaged objects from a deconstructor.  Also, the .NET runtime runs all finalization on a single thread and performance will be poor if too much work is done by a finalizer.  Therefore, the approach I took was to simply register some cleanup work to be done in a dictionary keyed by a GUID.  This GUID becomes the identifier for a stream.  When the stream deconstructor is called by the finalizer, the stream simply adds its GUID to a list of IDs for streams which are ready to be cleaned up.  This separate thread we have manually started monitors that list, then looks up the cleanup action and executes it.  This buys us three important things:
(1) The deconstructor is only referencing two things: a static dictionary which will not be garbage collected at any point during the execution of the application, and a value type of the stream itself (which is garbage collected along with the stream and will thus still be available when the deconstructor is called).
(2) The finalizer thread does as little work as possible.  A stream's deconstructor is simply responsible for adding it's ID to a list.  The rest of the cleanup work is done on the cleanup thread.
(3) The cleanup is done as soon as possible to allow the garbage collector to free up all of the memory we don't need anymore.

**Comment by jam40jeff** [comment]
> Do you have a simple example which demonstrates why this code is needed? Maybe I can figure out something different.

I will try to produce an example soon to demonstrate the behavior without having the cleanup thread.
