### ISSUE TITLE
Add Behavior class to Scala version as in the C# version

### ISSUE THREAD

**Issue by the-real-blackh** [SodiumFRP/sodium#127]
https://github.com/SodiumFRP/sodium/blob/master/c%23/src/Sodium/Sodium/Behavior.cs

**Comment by jam40jeff** [comment]
The `Behavior` class is mostly a rename of the `Cell` class with a couple methods removed.  The new `Cell` class contains the discrete cell behavior (and uses an underlying `Behavior` for its implementation in C#).

**Comment by newca12** [comment]
Fixed in 8c5b3d345fa6fba72ef8c8a7daff858c61958e15
