### ISSUE TITLE
Fix SampleLazy bug

### ISSUE THREAD

**Issue by jam40jeff** [SodiumFRP/sodium#131]
`SampleLazy` computes its value as part of the "last" phase of a transaction.  However, if the value constructed contains more FRP objects to add to the graph, this can cause a problem, as those objects will not have their prioritized actions run since the "last" phase is after the "prioritized loop".  The fix for this is to make a new "sample" phase which runs after all prioritized actions, but is still part of the "prioritized loop" so that it may add further actions to the prioritized queue to be run.

**Comment by jam40jeff** [comment]
Fixed by the following revisions:

73cbcf9
c1b2aa0
523c276
5a3504f

**Comment by the-real-blackh** [comment]
I've replaced this bug with ones for individual languages: #124 #125
