### ISSUE TITLE
C#: Add Transaction.isActive()

### ISSUE THREAD

**Issue by the-real-blackh** [SodiumFRP/sodium#133]
As discussed in #106, we should add a Transaction.isActive() method that returns true if we are currently within a transaction. This is useful for integration into non-FRP GUI libraries.

**Comment by jam40jeff** [comment]
@the-real-blackh Should this method return `true` if a transaction is open on any thread, or only on the same thread?

**Comment by the-real-blackh** [comment]
Only on the current thread. If it's open on a different thread, it should return false.
