### ISSUE TITLE
‘execute’ seems to cache

### ISSUE THREAD

**Issue by Twey** [SodiumFRP/sodium#14]
See http://lpaste.net/5885517651349864448 .  Behaviour occurs on an i5 running Linux (NixOS) with GHC 7.8.3 and

    Loading package transformers-0.3.0.0 ... linking ... done.
    Loading package array-0.5.0.0 ... linking ... done.
    Loading package deepseq-1.3.0.2 ... linking ... done.
    Loading package old-locale-1.0.0.6 ... linking ... done.
    Loading package time-1.4.2 ... linking ... done.
    Loading package containers-0.5.5.1 ... linking ... done.
    Loading package mtl-2.1.2 ... linking ... done.
    Loading package sodium-0.10.0.2 ... linking ... done.

Is this a bug?  I was certainly confused by it.

**Comment by the-real-blackh** [comment]
This bug is on my to-do list and I will get to it some time soon. Just need to get the book finished.

**Comment by the-real-blackh** [comment]
I'm not likely to fix this any time soon because I have deprecated the Haskell version of Sodium. I recommend people use Heinrich Apfelmus's Reactive Banana.
