### ISSUE TITLE
MapTo for Behavior/Cell

### ISSUE THREAD

**Issue by jam40jeff** [SodiumFRP/sodium#141]
@the-real-blackh I noticed that a pull request was recently created to add `mapTo` to `Cell` in the TypeScript version.  Is this something you think should be added for all languages or do you think it's an unnecessary addition?

**Comment by the-real-blackh** [comment]
Umm... I didn't pay that much attention when I first saw it... but actually I don't think there's any point to it at all. Certainly for a Behavior it's equivalent to a constant cell. For a Cell, it's almost equivalent to a constant cell.

**Comment by the-real-blackh** [comment]
I just realized that the author of it cancelled it. I put a comment on there saying I don't want this.

**Comment by jam40jeff** [comment]
Great, that was my opinion as well, although I figured maybe the author had a use case I hadn't imagined.
