### ISSUE TITLE
Memory management in C?

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium#148]
It seems that at least two implementations require a builtin memory management solution.

* Typescript: https://github.com/SodiumFRP/sodium-typescript/blob/master/src/lib/sodium/Vertex.ts
* Rust: https://github.com/SodiumFRP/sodium-rust/blob/master/src/sodium/gc.rs

Question... would it make sense to have a generic solution for all languages that require this, with a standard API, written in C?

My feeling is that most languages have some way of interfacing with that - e.g. typescript via emscripten/webassembly and rust via c bindings (or an api abstraction)

Just curious

**Comment by the-real-blackh** [comment]
C++ also needs such a solution. It isn't implemented yet.

If it were to be done, the way to do it would be the whole implementation of Node/Vertex including the garbage collector. I don't like the idea of bringing C into other languages due to the complexity. It seems to me the time would be better spent developing a test suite for Node/Vertex.

**Comment by clinuxrulz** [comment]
The real difficulty is Rust/C++ have stack-based allocation, and JavaScript/TypeScript do not. So js/ts can not use the strategy used in Rust. Rust/C++ can use the strategy used in js/ts but then you'll be forced to listen to all your sodium objects.

**Comment by clinuxrulz** [comment]
Stack-based allocation allows sodium objects that are sitting on the stack to be rooted in the GC. (It allows us to know they are in use)

**Comment by dakom** [comment]
OK closing this for now... I tried learning more about whether or not WebAssembly changes things... scrolled through some of this page and gave up: http://lambda-the-ultimate.org/node/5349

Interesting stuff in that thread though, worth checking out for anyone who's interested in this space.
