### ISSUE TITLE
Missing link to the blog

### ISSUE THREAD

**Issue by 45deg** [SodiumFRP/sodium#150]
On README.md,

>Drop by our blog at 
> http://reactiveprogramming.org/

However, this page shows something like PHP source code.

**Comment by f-z** [comment]
<img width="633" alt="screen shot 2019-02-25 at 05 07 12" src="https://user-images.githubusercontent.com/22554523/53315487-581f5900-38bb-11e9-9097-6515e9b04d3d.png">

**Comment by magneticflux-** [comment]
It seems to be a virus site now? I can only access the posts via the wayback machine.

**Comment by jam40jeff** [comment]
Removed blog link as it does not seem to be active anymore.
