### ISSUE TITLE
Sodium generates warnings with -Wshadow

### ISSUE THREAD

**Issue by antmd** [SodiumFRP/sodium#20]
Hi,

I use -Wshadow in my build, and sodium generates quite a few warnings with that flag switched on.

Given the complexity of the code, I can see the benefit of reducing shadowed variables to make the code easier to read.

I fixed the warnings in my branch: antmd/sodium@10b47a1f5136603ddcf5453a15f855c9fa93690c

The downside is using slightly ugly, renamed variables...what do you think?

Best Regards
--Anthony

**Comment by the-real-blackh** [comment]
This still needs to be fixed.

**Comment by the-real-blackh** [comment]
Fixed
