### ISSUE TITLE
Support base 4.8

### ISSUE THREAD

**Issue by geraldus** [SodiumFRP/sodium#29]
Hi, Steven! 
I've added sodium to Stackage recently. Now it's going to support GHC 7.10 RC1, and base have fixed 4.8 version there. Thus, sodium could not be built, because it depends on `base < 4.8`. Can you bump upper bound of dependency?
I could test build myself, but I need to learn how to write instructions for Travis first (I think this is the easiest way). Also I can try to find docker image with GHC 7.10 RC1 and test build with that.
What will you say?

**Comment by the-real-blackh** [comment]
Geraldus - thanks. I'm glad there's another change, because I need to update some links in the .cabal file. I'll get onto this in a couple of days.
