### ISSUE TITLE
Java tests do not build

### ISSUE THREAD

**Issue by cap11235** [SodiumFRP/sodium#31]
Due to the Java version of Sodium switching to calling things "Stream" and "Cell", while the tests use "Event" and "Behavior", they no longer build.

**Comment by butlermh** [comment]
Hi @Cap11235 I just submitted a PR that fixes this - #32 so the code should build at the command line. Best wishes!

**Comment by the-real-blackh** [comment]
Thanks for the bug report, cap11235
