### ISSUE TITLE
The name of filterNotNull

### ISSUE THREAD

**Issue by kt3k** [SodiumFRP/sodium#37]
Hi,

`filterNotNull` is a handy method, but the name sounds like the opposite of its actual behaviour.
`filterNull` sounds more appropriate to me for this method. How do you think?

Thanks,

**Comment by the-real-blackh** [comment]
It's named according to functional languages where you describe what you are keeping, e.g. in Haskell....

Prelude> filter even [1..5]
[2,4]

Other opinions?

**Comment by kt3k** [comment]
I see generic filter function/method behaves like that in most of languages, but if one make it into a single method including filtering condition, I think it's better to make it more natural as *English*.

This library has both filterNull and filterNotNull in it, and the meaning seems the opposite of sodium's.
http://docs.cascading.org/cascading/2.1/javadoc/cascading/operation/filter/FilterNull.html
http://docs.cascading.org/cascading/2.1/javadoc/cascading/operation/filter/FilterNotNull.html

**Comment by pyrtsa** [comment]
Another name suggestion with even less negation involved: `filterSome`
