### ISSUE TITLE
Port to Swift: Questions

### ISSUE THREAD

**Issue by letvargo** [SodiumFRP/sodium#40]
I think I'm going to try and port the Sodium library to the Swift programming language. Are you aware of anyone else doing this right now?

I am doing this because it looks like fun, but also because I am new to FRP and I think this would be an excellent way to learn more about it.

Because I am new to it, I may have a lot of n00b-type questions as I go along. Are you aware of any good forums for asking those kinds of FRP questions?

**Comment by the-real-blackh** [comment]
That's great! Nobody else has done anything with Sodium for Swift. I'd be very glad to make it part of the Sodium project, even if you don't finish it - someone else will.

FRP information is very scattered on the web. I'm hoping to make some sort of centre of gravity for FRP with my book. There are some questions on stackoverflow, and each FRP system developer has their own blog.

My book forum is at https://forums.manning.com/forums/functional-reactive-programming so I'd be happy to answer n00b questions there. My blog is http://reactiveprogramming.org/

**Comment by geraldus** [comment]
Sounds great!

Sat Jan 24 2015 at 2:03:19, the-real-blackh <notifications@github.com>:

**Comment by letvargo** [comment]
Thanks! I got the book through MEAP, and am through the first two available chapters.

**Comment by the-real-blackh** [comment]
I'm not sure where we talked about it, but I mentioned that I needed to make some changes that involved removing 'sampleNow' completely. I've now done this in the Java version.

**Comment by letvargo** [comment]
I am stalled out right now working on the port. I don't understand how Transaction works. Rather than bug you with endless questions, I've been waiting for the new chapters of the book to come out. I see that two new chapters are here and I'm sure that they will help.

In the meantime, this whole FRP thing has got me by the analytic nuts and I can't stop playing at an implementation of some kind. I put together a very simple native Swift FRP library and posted it on github.

https://github.com/letvargo/SimpleSwiftFRP

I would love to hear any thoughts that you might have, especially criticisms of any areas where it cheats on any aspects of FRP that you believe are essential.

P.S. if you think it is something that belongs in the Sodium project, I'll send a pull request, but it is different from Sodium in a number of ways, and also not really up to par yet.

**Comment by the-real-blackh** [comment]
Going through the process of writing an FRP system will teach you how it works, but be warned - it is possible to spend a lot of time on it. So I suggest you persevere and just use Sodium as a reference. I really want to get this book written, so I'm just going to focus on that for now. After that I will attempt to help you out and also spend some time tidying up Sodium. I'm happy to answer specific questions, though, because I can do that quickly.

**Comment by letvargo** [comment]
Thank you. I'll probably be here with more questions after I get through the newly released chapters.

**Comment by jam40jeff** [comment]
Closing since there is a Swift implementation now.
