### ISSUE TITLE
Port to kotlin

### ISSUE THREAD

**Issue by xgrommx** [SodiumFRP/sodium#41]
Do you plan port this library to [kotlin](http://kotlinlang.org)?

**Comment by the-real-blackh** [comment]
No, but only because I've never heard of kotlin. I definitely welcome anyone that wants to port it to any language. The Java version is the best reference implementation at the moment.

**Comment by xgrommx** [comment]
@the-real-blackh doesn't matter, exists java version. But I have yet another question. Do you plan port to javascript?

**Comment by the-real-blackh** [comment]
Yes, Javascript would be really good. It drives me crazy that it's dynamically typed, though. I won't get to it for for a while. Also, I am not very good at Javascript. So hopefully someone will beat me to it.

**Comment by xgrommx** [comment]
@the-real-blackh If you do not mind I could try to port it to the first typescript and then in javascript.

**Comment by the-real-blackh** [comment]
I would be really happy if you wanted to do that. Actually I didn't know about typescript, but it seems like it solves the problem!

**Comment by kentuckyfriedtakahe** [comment]
Typescript and then Javascript sounds like a splendid plan.

**Comment by romansl** [comment]
I implemented sodium in kotlin. It passes all sodium tests, but I made some breaking changes:
1. Stream is covariant. So `Stream<Object>` is `Stream<String>`.
2. Stream and Cell now interfaces. It is made to hide implementation details.
3. Stream uses Event<A>  - wrapper around value or error for holding A. So for example map has signature `fun <B> map(transform: (Event<A>) -> B): Stream<B>`

If you interested, check out here: https://bitbucket.org/roman/reactive/src

**Comment by the-real-blackh** [comment]
That is great!

**Comment by romansl** [comment]
Here: https://github.com/SodiumFRP/sodium-kotlin

**Comment by staltz** [comment]
If time ever allows me, I'd enjoy to implement Sodium in TypeScript. The JavaScript community is huge, so that might provide some visibility leverage to Sodium as well. I can't promise, but I'd like to. Doing a Java to TypeScript conversion really doesn't sound that hard, TypeScript looks like Java in many ways.

**Comment by xgrommx** [comment]
Will be nice :+1: @staltz This is implementation of Sodium in purescript https://github.com/clinuxrulz/purescript-sodium https://github.com/clinuxrulz/purescript-sodium

**Comment by the-real-blackh** [comment]
@staltz I would make TypeScript a high priority for Sodium. No-one has done any work yet as far as I recall and I won't have time for this myself for a little while yet.
