### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JamesTimms** [SodiumFRP/sodium#43]
Hi,
I'm thinking of using SodiumFRP in my Major Project (the Java implementation mainly) for my degree but I can't find any license for your library.
Am I ok to just go ahead and use SodiumFRP with my Major Project?

**Comment by the-real-blackh** [comment]
Oh - sorry about that. I'll check one in. It's BSD3.

**Comment by the-real-blackh** [comment]
Actually it is there: It's in a file called COPYING

**Comment by the-real-blackh** [comment]
I have made a small change to it and brought the dates up-to-date. The change is that there may be other licences in portions of the code, because some contributors may want to put their part under a different licence.

**Comment by JamesTimms** [comment]
Ah I missed that. Thank you.
