### ISSUE TITLE
Wiki out of date?

### ISSUE THREAD

**Issue by JamesTimms** [SodiumFRP/sodium#47]
Hi,

Just read the wiki and it seems out of date as it mentions the library is for C++ and is called Lithium?
https://github.com/SodiumFRP/sodium/wiki/Introduction
Not sure what to change the wiki to so thought I'd just flag this as a potential issue.

**Comment by the-real-blackh** [comment]
Thank you. Sorry about the delay in replying.

I'll sort that out when I overhaul the project after I've finished writing the book (soon).
