### ISSUE TITLE
Splitting the libraries into their own repositories

### ISSUE THREAD

**Issue by grahamreeds** [SodiumFRP/sodium#51]
While having everything under the umbrella of SodiumFRP is maybe nice it makes little sense for me, as a C++ developer, to download the source in Java, Haskell, C#, Scala, Rust, etc.

I could download what I need and delete the rest but I prefer to handle my dependencies in Git via submodules.  I have got a short distance on that via help at StackOverflow[1] but not found the rest of the way yet.

So any chance of seeing sodium++, jsodium, iron-sodium, etc.?

[1] http://stackoverflow.com/questions/29099736/checkout-a-git-subdirectory-into-a-particular-folder

**Comment by the-real-blackh** [comment]
First of all, sorry about the delay. I did not get notified that you raised this issue for some reason.

When I've finished writing the book (soon) my goal is to overhaul the Sodium project. I am not quite sure what to do about this, but I'll figure it out.

By the way, there are memory-related issues with the C++ version that are going to be quite challenging to solve. I need to devote some time to that.

**Comment by grahamreeds** [comment]
What are they in particular? I have a couple of toy projects and recreated
the petrol pump in C++ but didn't notice anything, but then again I wasn't
looking too hard

Maybe I can have a look if you can give me a snippet that recreates the
issue.

GR

**Comment by the-real-blackh** [comment]
The issue is that behavior_loop and event_loop construct cyclic smart_pointers, and these can't ever be cleaned up. If you use that inside a switch, you'll get a memory leak.

I've started on a 'v2' version that has a tricky cycle detector, but the bugs are not out yet.

**Comment by jhr007** [comment]
FWIW, Selenium is a single repo, multiple language project. 

Might be worth taking a look at how they solved packaging to multiple languages. For C# they build documentation and a Nuget distribution. 
https://github.com/SeleniumHQ/selenium

**Comment by the-real-blackh** [comment]
Thanks for that suggestion. I will figure out what to do and sort this out some time soon.

**Comment by grahamreeds** [comment]
As I pointed out previously, adding as a submodule in git means you pull in
everything.

Selenium is not a good example as that is a tool whereas this is a library.

GR

**Comment by the-real-blackh** [comment]
I've separated sodium-c++ into a its own repo 'sodium-cxx'.
