### ISSUE TITLE
"thread blocked indefinitely in an MVar operation" when using snapshot, listen and mdo

### ISSUE THREAD

**Issue by ocharles** [SodiumFRP/sodium#52]
The following code results in a runtime exception:

```haskell
import FRP.Sodium

main :: IO ()
main =
  do sync (mdo listen (snapshot (,) never v)
                      (const (putStrLn "Listen"))
               v <-
                 accum 0 (fmap (const (+ 1)) never)
               return ())
```

My expectation is that this is should run fine, yet it results in a "thread blocked" exception.

**Comment by the-real-blackh** [comment]
First of all, sorry about the delay. I didn't get notified for some reason about this issue being raised.

Yes, this should work fine. When I have finished the book, I will have time to attend to this issue.

**Comment by the-real-blackh** [comment]
I've deprecated the Haskell version of Sodium now. Please use Heinrich Apfelmus's Reactive Banana.
