### ISSUE TITLE
Minimum Java Compilation Version

### ISSUE THREAD

**Issue by ersin-ertan** [SodiumFRP/sodium#54]
As quoted from the Java README:
"sodium.jar can be built with Java 5 or higher..."
"At the time of writing, you need to use the Project Lambda version of Java 8..."

Does this conflicting statement need correcting?

My goal is to play around with Sodium in the Android environment, which is limited to Java 1.7.
I have tried to compile the Android Project(modifying app.build compileOptions to 1.8) with JDK 1.8, only to get:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

Trying to compile sodium with 1.7 yields the keyword Optional not to be found.

**Is it safe to say/change the documentation, removing the note about less than JDK 1.8 compatibility?**
P.S. A workaround for 1.7 could use Guava's optional as a replacement in the Sodium framework.

**Comment by the-real-blackh** [comment]
I would like to fix this, but I am writing a book which is keeping me very busy. It would not be difficult to reinstate 1.5 compatibility, but I have no idea how to do conditional compilation in Java projects. Do you know, by any chance? That would save me some time.

**Comment by ersin-ertan** [comment]
My search came up with No, but these some proposed alternatives:
[using a static final boolean](http://www.javapractices.com/topic/TopicAction.do?Id=64)
and [annotation processing](http://tutorials.jenkov.com/java/annotations.html) for Compiler instructions, Build-time instructions, Runtime instructions, which is out of my scope of knowledge.

**Comment by the-real-blackh** [comment]
Thanks. I think there might be another way. I'll get to it some time soon.

**Comment by grahamreeds** [comment]
Why bother with conditional compilation?

If the only language feature that Sodium relies on is Optional then why
don't you implement a version of it locally?

And that goes for the C++ version too - I have all libraries local to the
project with the project. I am a believer that with the compiler and access
to source control you should be able to build the project. Seems that the
C++ version has just optional from boost.

GR

**Comment by the-real-blackh** [comment]
The only issue is java.util.Optional. Apart from that, it's easy to remove all the lambda syntax. Perhaps I can do it so that there's a sodium.jar and sodium-1.5.jar that contains java.util.Optional. On 1.8 you should be able to include only sodium.jar. I'll see if that works.

**Comment by the-real-blackh** [comment]
commit 5bfa7bd6a0887c333ec37f5b13d9ea59b85867f1
Author: Stephen Blackheath <docks.cattlemen.stephen@blacksapphire.com>
Date:   Wed Jul 8 21:14:10 2015 +1200

    Fix issue #16: Java version does not build on 1.5 any more.
    Fix issue #54: Minimum Java Compilation Version
    We now support Java 1.5.
