### ISSUE TITLE
Java: why unsafeAddCleanup not guarded by lock?

### ISSUE THREAD

**Issue by romansl** [SodiumFRP/sodium#56]
What if `unsafeAddCleanup` being called from two or more threads on the same time. We have a risk of demaging ArrayList content.

**Comment by the-real-blackh** [comment]
Ah, you're right. I checked this fix in:

commit a2f93855ada8d86093cf284a5fafd86cc5e5af7e
Author: Stephen Blackheath <docks.cattlemen.stephen@blacksapphire.com>
Date:   Wed Jul 8 17:08:52 2015 +1200

    Issue #56: Java: why unsafeAddCleanup not guarded by lock?
    What if unsafeAddCleanup being called from two or more threads on the same
    time. We have a risk of demaging ArrayList content.
    ---
    Yes, this is true. I've fixed a case where it could go wrong and documented
    the assumptions that are being made.
