### ISSUE TITLE
The other way to make loops.

### ISSUE THREAD

**Issue by romansl** [SodiumFRP/sodium#59]
For me it was hard to undertand why we use `CellLoop` and `StreamLoop`. Now I understood, but I think the api is inconvenient. Sodium api builds graph of hierarhical nodes, used to produce computations. For building the graph there is several ways. I suggest this:

Impossible code:
```kotlin
            val sink = streamSink<Boolean>()
            val gated = sink.gate(held)
            val held = gated.hold(true)
```

Here we build `gated` stream. It passes boolean values until meets `false`. It is impossible because of `held` needs reference to `gated` and `gated` references to `held`. To eliminate this problem is not necessary to use `StreamLoop`. We can simply pass the `StreamSink` to `gate`.

```kotlin
            val sink = streamSink<Boolean>()
            val gated = streamSink<Boolean>()
            val held = gated.hold(true)
            sink.gate(gated, held)
```

It produces shorter graph of nodes compared to `StreamLoop` (3 nodes vs 4 nodes). And we no longer need in `Loop` classes.

What do you think?

**Comment by the-real-blackh** [comment]
How do you write this without CellLoop?

```java
Stream<Unit> sCount = ...;
CellLoop<Integer> count = new CellLoop<>();
count.loop(sCount.snapshot(count, (u, c) -> c + 1));
```

**Comment by romansl** [comment]
```
            val sink = streamSink<Unit>()
            val outCount = streamSink<Int>()
            val count = outCount.hold(0)
            sink.snapshot(count, outCount) { u, c -> c.value + 1 }
```

**Comment by the-real-blackh** [comment]
So this is a form of snapshot that pushes the value? So you'll need a normal and a pushing variant of each? What about this...

```java
Stream<Integer> increment(Stream<Integer> s) {
    return s.map(i -> i + 1);
}
...
Stream<Unit> sTick = ...;
Stream<Integer> sNext = ???;  // How do we loop this so it's equivalent to sNext0?
Cell<Integer> count = sNext.hold(0);
Stream<Integer> sNext0 = s.increment(sTick.snapshot(count));
```

Assume increment() is complex. Do we need a pushing and pulling variant of it too? (Do we need to write all our code twice in case the caller wants to loop something?)

```java
void incrementPushingVariant(Stream<Integer> s, StreamSink<Integer> out) {
    return s.map(i -> i + 1, out);
}
```

Another thing to bear in mind is that FRP has the property that if you want to know what the dependencies of a piece of code are, you just look at the code. All that searching the whole program is gone. Once you can pass sinks around, that doesn't work any more. The source of a stream's data could be anywhere where the sink is in scope.

**Comment by romansl** [comment]
I see. You right.
