### ISSUE TITLE
Idea: defer(Executor)

### ISSUE THREAD

**Issue by romansl** [SodiumFRP/sodium#61]
I implemented the function that sends message to another thread. I called it `onExecutor`. Later, I noticed that it is very similar to `defer` with Executor parameter. This function is widely used in practice. May be you add it to Sodium?

**Comment by the-real-blackh** [comment]
Thanks for all these questions. It's great! Can you give me a bit more information about onExecutor? Where do I find the code for it?

Would you like to check your kotlin version into the Sodium repo? I've invited you as a member of the project.

**Comment by romansl** [comment]
Like original `defer`, but executes transaction on executor.
```kotlin
    override fun defer(executor: Executor): StreamImpl<A> {
        val out = StreamWithSend<A>()

        val listener = Transaction.apply2 {
            listen(it, out.node) { trans2, value ->
                executor.execute {
                    Transaction.apply2 {
                        out.send(it, value)
                    }
                }
            }
        }

        return out.addCleanup(listener)
    }
```

**Comment by the-real-blackh** [comment]
1. This is different to defer, because defer makes a guarantee that the new transaction will occur before any other event. This introduces non-determinism, and a lot of the point of FRP and functional programming is to get rid of non-determinism.

2. Threads are not part of the FRP paradigm. What thread things run on is an operational issue, and doesn't belong in an FRP API - at least, not in that form.

**Comment by romansl** [comment]
I understood. You right. From this point of view it would be better to add `listen(Executor, (Event<A>) -> Unit)`. It turns out that IO is stop-point for FRP computations. This sad because my code has a lot of such places.

We must figure out how identify such sections. How I must use functions like `onExecutor`?

1.
```
clicked().io().map().io().listen(...)
```

2.
```
Operational.io(Operational.io(clicked()).map()).listen(...)
```

3.
```kotlin
val io1 = streamSink()
val io2 = streamSink()
clicked().io(io1)
io1.map().io(io2)
io2.listen(...)
```

**Comment by the-real-blackh** [comment]
The first one is nicest. I am aware that we should add more helpers to Sodium, but I really want them to be kept to an absolute minimum. So we can add them after much discussion and thought.

**Comment by romansl** [comment]
More explaination: the `io` function is abstract io operation, for axample `onExecutor` or `queryFromHttp`

Thhe first example looks nice, but syntax of io oparations does not differ from true FRP primitives. It is bad. What if such function accidentally occures in true FRP flow? The code can become broken, and we dont even know why.

The io operations must be stoppers like `listen`. Thats why i like third example.

**Comment by romansl** [comment]
Or may be io operations must just return `Stream<Stream<A>>`?

**Comment by the-real-blackh** [comment]
Yes. Also remember that even though it would make the user's code nicer, the FRP system doesn't really need this helper. The user could just figure out their own way of doing it using StreamSink, listen and addCleanup.

**Comment by the-real-blackh** [comment]
I'm assuming an IO operation is a function from ```Stream<A>``` to ```Stream<B>```. For each request of type A there's a response of type B, but they could be interleaved.

**Comment by romansl** [comment]
4.
```
clicked().flatMap { io1() }.map().flatMap { io2() }.listen()
```
But here we have buggy `flatMap` from antother issue.

**Comment by romansl** [comment]
5.
```
io2(io1(clicked()).map(...)).listen()
```

**Comment by romansl** [comment]
6.
```kotlin
class IO<A> : () -> A

fun Stream<Unit>.io1(): Stream<IO<String>>
fun Stream<IO<String>>.io2(): Stream<IO<Int>>

clicked().io1().ioMap(...).io2().ioListen(...)
```

**Comment by the-real-blackh** [comment]
Maybe one day Java will have extension methods!

**Comment by romansl** [comment]
Thats why I using kotlin.

**Comment by the-real-blackh** [comment]
That's why I use Haskell.
