### ISSUE TITLE
FRP code is write-only

### ISSUE THREAD

**Issue by romansl** [SodiumFRP/sodium#65]
The problem: FRP (and m.b. functional) code is hard to read. Even in simple constructions. For example:

FRP code:
```kotlin
    val sink = Sodium.streamSink<Int>()
    val cell = Sodium.tx {
        val cellLoop = Sodium.cellLoop<Int>()
        val cell = sink.filter {
            it.value > cellLoop.sample().value
        }.hold(0)
        cellLoop.loop(cell)
        cell
    }
```

It is impossible to tell at a glance what it code does. For this we need to understand what does each primitive.

Compare it with imperative code:
```kotlin
    var cellVar: Int = 0

    public fun send(value: Int) {
        if (value > cellVar) {
            cellVar = value
            onCellVarChanged(value)
        }
    }

    private fun onCellVarChanged(value: Int) {

    }
```

Are there any empirical rules for reading code like this? Or may be writing more clear FRP code?

The only way I se here (for now) is to write comment lines for all FRP constructions. But what if code has bug in it? Comments little helps in such cases.

**Comment by the-real-blackh** [comment]
There two issues here:

* First, you are used to imperative code but not to FRP code. This gives imperative code an unfair advantage.

* Second, the syntax of FRP is terrible. I talk about this briefly in the book. It could be improved hugely with some kind of preprocessor. It'd be great to standardize that.

* FRP is semantically simpler and easier to make modular. The advantages increase as the code size gets bigger.

**Comment by romansl** [comment]
Agree, so I need the rules how to write and read FRP code. 

This syntax can not be simplier in java. Mb in kotlin. The one thing I really dont like is loops. kotlin can make this part less verbose, but not totally eliminates the problem:

```kotlin
    val sink = Sodium.streamSink<Int>()
    val cell = Sodium.tx {
        val cell = cellLoop<Int>()
        cell loop sink.filter {
            it.value > cell.sample().value
        }.hold(0)
        cell
    }
```

**Comment by the-real-blackh** [comment]
That's why the best solution is a preprocessor. In Haskell loops are just forward/cyclic references, enabled with the keyword 'rec':
```haskell
(sink, sendSink) <- newEvent
rec
    cell <- hold 0 $ filterJust
                   $ snapshot (\c s -> if c > s then Just s else Nothing) sink cell
```
A preprocessor would also allow for auto-lifting and type inference, e.g.
```java
Cell<Integer> a = Cell.lift((b_, c_) -> b_ + c_, b, c)
```
becomes
```
a <- b + c
```

**Comment by romansl** [comment]
There is FRP language: http://elm-lang.org/

**Comment by the-real-blackh** [comment]
ELM has the same syntax as Haskell, so it has type inference, which is great. But it doesn't have auto-lifting and there are probably other things we can improve.

**Comment by ritschwumm** [comment]
scala.react, as described in http://infoscience.epfl.ch/record/176887/files/DeprecatingObservers2012.pdf provides some much more readable syntax, at least for behaviours. the way it's done is not exactly pretty, but with some macros - like the ones https://github.com/pelotom/effectful provides - the same could be achieved in a much better way.

**Comment by the-real-blackh** [comment]
Of course I would love to improve FRP syntax, but given that Sodium has a lot of work to do yet to get things working on multiple languages, I am going to consider this area not within the immediate scope of Sodium for now and close this bug.
