### ISSUE TITLE
`value beh` seems to spuriously skip new values

### ISSUE THREAD

**Issue by pyrtsa** [SodiumFRP/sodium#67]
To demonstrate how [`accum` breaks down in case of coincident `Event` firings](https://github.com/SodiumFRP/sodium/issues/39#issuecomment-122527053), I noticed a strange issue when trying to listen to the `value` of a `Behavior`. The following code:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import FRP.Sodium

main :: IO ()
main = do
    (ints :: Event Int, fireInt) <- sync newEvent
    sums <- sync $ accum 0 $ (+) <$> ints
    unreg <- sync $ do
        un1 <- listen ints         (\x -> putStrLn $ "add:   " ++ show x)
        un2 <- listen (value sums) (\x -> putStrLn $ "total: " ++ show x)
        return $ un1 >> un2
    sync $ fireInt 10
    sync $ fireInt 20
    sync $ fireInt 30 >> fireInt 40
    sync $ fireInt 100 >> fireInt 1000000 >> fireInt 0
    unreg
```

is supposed (with the current denotational design) to print the following lines:

```txt
total: 0
add:   10
total: 10
add:   20
total: 30
add:   30
add:   40
total: 70 -- (this obviously would be 100 if accum got it right, but that's not the issue here)
add:   100
add:   1000000
add:   0
total: 70
```

However, two subsequent runs of the same script got different (!) results on my GHCI:

```txt
λ> main
total: 0
add:   10
total: 10
add:   20 -- missing "total: 30" here!
add:   30
add:   40 -- missing "total: 70" here!
add:   100
add:   1000000
add:   0 -- missing final "total: 70" here!
λ> main
total: 0
add:   10
total: 10
add:   20
total: 30
add:   30
add:   40
total: 70
add:   100
add:   1000000
add:   0 -- missing final "total: 70" here!
```

Changing `(value sums)` into `(updates sums)` correctly made the initial `total: 0` go away and fixed the inconsistency at least in my test runs:

```
λ> main'
add:   10
total: 10
add:   20
total: 30
add:   30
add:   40
total: 70
add:   100
add:   1000000
add:   0
total: 70
```

What could be happening here? Something odd in the [definition of `value`](https://github.com/SodiumFRP/sodium/blob/master/haskell/src/FRP/Sodium/Plain.hs#L274-L278)?

**Comment by the-real-blackh** [comment]
Thanks for finding this bug. Memory management/finalizers are somewhat tricky. I'm trying to finish the book at the moment but when I've done that, I intend to give all versions of Sodium the love they deserve. The Haskell version needs a fair bit of it.

**Comment by robotbrain** [comment]
Can confirm, in my case the dropped events prevent my irc setup from starting the irc exchange

**Comment by the-real-blackh** [comment]
I'll find some time to fix this.

**Comment by robotbrain** [comment]
Also updates is just as inconsistent for me

**Comment by the-real-blackh** [comment]
I've decided to deprecate the Haskell version of Sodium. Please use Heinrich Apfelmus's Reactive Banana.
