### ISSUE TITLE
Java: easy explaination of `loop`

### ISSUE THREAD

**Issue by romansl** [SodiumFRP/sodium#68]
I found that it is easier to understand what the `loop` is: invert it signature.

The `a.loop(b)` is just stream forwarding events from `b` to `a`. Something like this. I think it would be nice to add this definition to the book. Also need to specify that there is no difference between the subscription to `a` and `b`.

**Comment by the-real-blackh** [comment]
Not going to fix this. Now that the book is written it's set in stone.
