### ISSUE TITLE
Behaviour propagation

### ISSUE THREAD

**Issue by elaye** [SodiumFRP/sodium#73]
Hello,
I recently discovered Sodium and it's amazing what it's possible to do with it! However, I'm facing a problem at the moment that makes me think that I still don't quite understand how it really works. 

I'm trying to implement a "reactive cube" where for instance the width of the cube is controlled by a `Behaviour`. My cube is represented like this:

    data RCube = RCube
	    { cubeSize :: Behaviour Float
	    , changeCubeSize :: Float -> Reactive ()
	    , mesh :: RMesh 
	    }

And I create one with this function:

    newRCube :: Point -> Float -> App RCube
    newRCube p s = do
	    (eSize, pushSize) <- io $ sync $ newBehaviour s
	    mesh <- io $ newRMesh LineStrip
	    io $ sync $ listenTrans (updates eSize) $ \s ->
		    scaleMesh mesh $ scaleMatrix $ Vec3 s s s

	    --io $ sync $ listen (updates eSize) print
	    return $ RCube eSize pushSize mesh

And for the `RMesh`:

    data RMesh = RMesh
        { mode :: GL.PrimitiveMode
        , model :: Behaviour Mat4
        , scaleMesh :: Mat4 -> Reactive ()
        ...
        }

    newRMesh :: GL.PrimitiveMode -> IO RMesh
    newRMesh mode = do
        (eScale, pushScale) <- sync $ newBehaviour idMatrix
        --idem eRotation, eTranslation
        let eModel = (multmm) <$> ((multmm) <$> eScale <*> eRotation) <*> eTranslation
        --sync $ listen (updates eScale) print
        ...
        return $ Mesh mode eModel pushScale ...

Now with this I try to change the size of the cube with respect to time like this:

    main :: IO ()
    main = runApp app

    app :: App ()
    app = do
	    -- OpenGL stuff
	    cube <- newRCube (Point 0 0 0) 500
	
	    io $ sync $ changeCubeSize cube 300
	    io $ sync $ changeCubeSize cube 400
	    io $ sync $ changeCubeSize cube 200

	    forever $ do 
		    t <- io $ getElapsedTime
		    let s = realToFrac $ t * 100
		    io $ sync $ changeCubeSize cube s
		    draw cube
                    ...

What I'm trying to do is to propagate the change of the cube size to the mesh scale. The behaviour of my program is inconsistent and I have absolutely no clue of where it can come from. If I call `changeCubeSize` before the `forever` in my app function, the cube size does change but not every time: if I call `changeCubeSize` mutliple times the last calls won't do anything. And the call in the `forever` doesn't do anything. I suppose there is a better way to do what I'm trying to do but I can't see it...

**Comment by the-real-blackh** [comment]
Unfortunately in ghc-7.10 Sodium isn't working properly due to (I think) a change in the way mkWeakIORef works. I need to spend some time fixing this bug and bringing the Haskell version up-to-date. (I'm writing a book so that's been keeping me a bit busy.) The checked in version is hacked so it leaks memory but gives the right answers.

You could use an earlier ghc until I've fixed it, or use Reactive Banana instead, which is actually almost identical to Sodium except that its interface to I/O is a bit different.

**Comment by elaye** [comment]
Thank you for the quick answer! I use ghc-7.6.3, so it should work, no? Which version of ghc do you recommend?

**Comment by the-real-blackh** [comment]
That should work. I'll test your code out and get back to you shortly.

**Comment by the-real-blackh** [comment]
You have to ensure the IO action returned by 'listen' is kept alive. This might be your problem. This is not necessarily straightforward in Haskell. I am planning an improvement for this.

**Comment by elaye** [comment]
Ok. I'm still a beginner in Haskell and FRP so I don't know where to start to solve this problem. 

For now I solved it like this:

    data RCube = RCube
	    { changeCubeSize :: Float -> Reactive ()
	    , mesh :: RMesh 
	    }

    newRCube :: Point -> Float -> App RCube
    newRCube p s = do
	    mesh <- io $ newRMesh LineStrip
	    return $ RCube eSize (changeSize mesh) mesh

    changeSize :: RMesh -> Float -> Reactive ()
    changeSize mesh s = scaleMesh mesh $ scaleMatrix $ Vec3 s s s

The problem is that I can't listen to a change in the cube size.

By the way, can you recommend some resources to understand FRP and Sodium? Will your book cover the Haskell implementation of Sodium?

**Comment by the-real-blackh** [comment]
You should be able to listen to changes in the cube size. I'm sorry - I can't quite understand your code. But if the field cubeSize :: Behavior Float is available, you can listen to it.

Keep trying with FRP. It takes a little while to understand the different way of doing things, but it does get easy. I'm sorry you'll have to wait for me to make some improvements. If you have trouble with listeners getting cleaned up, you can use this trick:

```haskell
    unlisten <- sync $ listen ...
    forkIO (threadDelay 86400000000 >> unlisten).
```

I know this is very ugly. My plan is to rename listen to listenWeak, and add a new 'listen' which stays alive if the caller deallocates the listener.

My book does not cover the Haskell implementation. It uses Java instead. The book is about FRP and isn't specific to Java and the code would be easy to translate to Haskell in your head. FRP looks similar in any language. The book does talk a lot about functional programming concepts, which Haskell programmers already know.

Some time soon I plan to do some introductory videos (again, Java-based) to promote the book but they'll be useful without the book.

**Comment by grahamreeds** [comment]
Maybe an appendix covering other language implantations and how they
compare to the canonical Java version?

**Comment by elaye** [comment]
Listening to events works well. However I have a problem when I want to propagate a behaviour, I'm sorry if I was not clear enough I'll try to explain my problem better. 

Let's say I have a cube and I'd like to control its size with a `Behaviour` so I made a `RCube` data type that contains a size behaviour (`cubeSize :: Behaviour Float`) and a function to push a new size (`changeCubeSize :: Float -> Reactive ()`). Now to draw this cube on the screen I draw a mesh using OpenGL. So, to change the size of my cube I just multiply the vertices of my mesh with a scaling matrix. To represent a mesh, I have a `RMesh` data type that contains a scaling matrix (`model :: Behaviour Mat4`) and a function to push a new matrix (`scaleMesh :: Mat4 -> Reactive ()`). 

What I am trying to achieve is this: when I change the cube size (with `changeCubeSize`) I want the scaling matrix of my mesh to change as well. So to propagate the behaviour the idea is this:

    sync $ listen (updates eSize) $ \s
        sync $ scaleMesh mesh $ scaleMatrix $ Vec3 s s s

Obviously this doesn't work, as indicated in the documentation, because you can't use a `sync` in a `listen`. So I tried something with `listenTrans`:

    sync $ listenTrans (updates eSize) $ \s ->
        scaleMesh mesh $ scaleMatrix $ Vec3 s s s

This is where I have problems. It works a little and rapidly stops. So yes it seems you are right about the listeners getting cleaned up. I tried your trick with the `forkIO` but the result is the same.
Do you see another way of doing what I am trying to do with sodium? I don't know how to avoid using `listenTrans`.

**Comment by the-real-blackh** [comment]
I understand your question now. The short answer: You are not allowed to use sync inside a listener handler at all, and listenTrans would be used for I/O. You should never call 'send' from a listenTrans handler. There are two reasons for this:

1. If people can (effectively) write their own primitives, it's impossible to guarantee correct FRP semantics and compositionality.

2. It's impossible for Sodium to track dependencies with this style, so it's impossible for it to guarantee correct execution order in all cases.

The Java version handles the situation a bit better - it throws an exception. I'll make this and some other improvements in the Haskell version when I find the time to do it.

If you want scaleMesh to be modified by (updates eSize) then you need to write its value in terms of (updates eSize). It should look something like this:

```haskell
newRMesh :: GL.PrimitiveMode -> Event Mat4 -> IO RMesh
newRMesh mode eScale = do
    --idem eRotation, eTranslation
    let eModel = (multmm) <$> ((multmm) <$> eScale <*> eRotation) <*> eTranslation
    --sync $ listen (updates eScale) print
    ...
    return $ Mesh mode eModel ...
```

Events and behaviors are *always sources of information*. The 'push' action of newBehavior / newEvent is only for I/O, never for logic. This may be a completely different way of doing things from what you're used to.

Is that making sense? Please ask if not.

**Comment by elaye** [comment]
Yes it makes a lot of sense.
Haha it's so simple! To change the way to look at things is hard though.
Thanks for your patience and your useful answers!
