### ISSUE TITLE
Labels on some diagrams are not consistent with test cases

### ISSUE THREAD

**Issue by zudov** [SodiumFRP/sodium#76]
In document on denotation the labels for arrows do not correspond to let binding names in test cases.

For example, in "Updates" section test cases feature names `c` and `s`:
```haskell
let c = Hold 'a' (MkStream [([1], 'b'), ([3], 'c')]) [0]
let s = Updates c
```
But the diagram is using labels `b` and `s1`.

Here is a (possibly incomplete) list of sections with broken diagrams:

- Snapshot
- Updates
- Value
- Constant
- Hold

**Comment by the-real-blackh** [comment]
Thanks!
