### ISSUE TITLE
A boundary case of `Value`

### ISSUE THREAD

**Issue by zudov** [SodiumFRP/sodium#77]
The "Value" section of denotation document says:

> Note there is a boundary case: where a step occurs at t0, the initial value and the first step value are output as simultaneous events.

And then there is a [test case](https://github.com/SodiumFRP/sodium/blob/master/denotational/sodium.hs#L57) which addresses that boundary case:

```haskell
let c = Hold 'a' (MkStream [([0], 'b'), ([1], 'c'), ([3], 'd')]) [0]
let s = Value c [0]
assertEqual "s" [([0],'b'),([1],'c'),([3],'d')] (occs s)
```

So, even though denotation says that "initial value and the first step value are output as simultaneous events" the implementation just throws away the initial value and outputs the first step value essentially behaving like `updates`.

I would expect something like:
```haskell
[([0], 'a'),([0],'b'),([1],'c'),([3],'d')] 
```

Please prove me wrong here, because I am freaked out a little.
Thanks.

**Comment by zudov** [comment]
Here is a valuable explanation from @pyrtsa 

> If the Behaviour's value never observably was 'a', then the stream of values should not contain 'a' either. So if something is off, it's the text, not this part of the denotation spec.

Which helped me to fix my understanding.
Further quoting the document:


 > [Value is] Like Updates except it also fires once with the current cell value at the time t0 when it is constructed.

So the implementation does the right thing, it fires at time `[0]` with the cell value at that moment `('b')`.

Perhaps the document needs some improvement. Along the lines of:
"Note there is a boundary case: where a step occurs at t0, the first step value is output since it's the value of the cell at the time t0."

**Comment by the-real-blackh** [comment]
There has been a semantic change in which simultaneous events are no longer allowed, so the whole "Note there is a boundary case..." refers to the old semantics and needs to be removed, so I've removed it.
