### ISSUE TITLE
[c++] Convenience method to return constant from map()

### ISSUE THREAD

**Issue by notlion** [SodiumFRP/sodium#80]
First off, thanks for the book and library! I'm just starting to wrap my head around FRP and it's very helpful to have a reference and guide.

I'm finding myself doing things like this a lot:

```
event.map<bool>([](const auto &e) { return true; })
```

Unfortunately the C++ lambda syntax makes this a bit more verbose that is necessary. Is there a simpler way to always return a constant from map()? Maybe something like `event.constant(true)` or `event.always(true)`? Is this something that makes sense?

**Comment by the-real-blackh** [comment]
Yes, I want that too. I am thinking of calling it .mapTo() which is used in other FRP systems. I am still a bit busy, so if you'd like to supply a patch, I'll take it. I'm going to do some major work on all the versions to bring them up to the standard of the Java one.

**Comment by notlion** [comment]
Thanks for the merge!
