### ISSUE TITLE
User Group For Sodium

### ISSUE THREAD

**Issue by hugo-bluecorn** [SodiumFRP/sodium#82]
Hi

I would like to know where is the list or slack for the Sodium community?

**Comment by adishavit** [comment]
https://forums.manning.com/forums/functional-reactive-programming

**Comment by the-real-blackh** [comment]
The Manning forum and this github is it for now. I'm open to suggestions.

**Comment by hugo-bluecorn** [comment]
Would a google group work?

**Comment by the-real-blackh** [comment]
I am not so keen on Google Groups - but not sure why. How about something a bit more up-to-date like http://discourse.org/? So here's a job for everyone interested - find out what the best option is!

**Comment by RobertWalter83** [comment]
it's kinda hard to determine a "best" option if we do not discuss what we want. I'm not keen on Google Groups either, I don't find them particularly clear, but they do work. Discourse I do not know, but it looks quite interesting. I suggest to either create a group and see how it goes, or discuss what we (or you in particular, Stephen), are looking for.
On a side note, I started a repository where I check-in a bunch of commented examples using Sodium. I'm happy to get feedback. The latest addition is a live C# scripting application: https://github.com/RobertWalter83/SodiumSamples#livescripting

**Comment by the-real-blackh** [comment]
Github is almost good enough. The only problem is that questions like "how do you do X?" or "why doesn't my program work?" aren't really issues that can or should be closed when they're resolved. So we just need something simple where you can open a new topic with a flat thread.

**Comment by RobertWalter83** [comment]
Has anyone experience with gitter? It seems to be more like a chat, although it persists all messages and it seems to have a good integration with GitHub.
I don't think the issues section here is meant to be a place to gather "how to" information or, nor will people use it as such.

**Comment by the-real-blackh** [comment]
No, but I'll take a look.

**Comment by the-real-blackh** [comment]
I've set up [Sodium user forums](http://sodium.nz/). You can use github logins. Please try it out and see what you think.

**Comment by RobertWalter83** [comment]
Thanks Stephen! I'll soon make use of it!

**Comment by RobertWalter83** [comment]
I kicked off the user forum with a first (well, second), [entry](http://sodium.nz/t/live-scripting-c-with-sodium/33). Let's spread the word :)
