### ISSUE TITLE
[c++] Sending inside a callback should throw

### ISSUE THREAD

**Issue by notlion** [SodiumFRP/sodium#87]
I've run into situations in my own code where cycles are being created due to send() being called inside of listeners. The resulting infinite loop can be a bit hard to track down. The stack trace is really large and not super helpful. It would be great if this type of error was caught early by the library.

**Comment by the-real-blackh** [comment]
The Java version does this. I intend to make them all conform. What language are you using?

**Comment by notlion** [comment]
Sorry I hinted it in the title, but should have made it clearer. I'm using the C++ version.

**Comment by the-real-blackh** [comment]
Doh. OK - I'll fix it!

**Comment by the-real-blackh** [comment]
Fixed in https://github.com/SodiumFRP/sodium-cxx/commit/0c6e249e194724165e29f0163df12f66a074fccb
