### ISSUE TITLE
RunInitialTransaction was removed from C# version

### ISSUE THREAD

**Issue by Ziriax** [SodiumFRP/sodium#96]
I'm making a little framework to combine Sodium FRP with XAML-style MVVM.

When a WPF binding changes a view-model property, I used  `Transaction.RunInitialTransaction(() => _sink.Send(value))` to send the new property value to a Sodium sink, but only if no transaction is currently running. That's because when Sodium writes new values to `Cell`s when it closes the transaction, the new values will again update the WPF bindings, but these changes must be ignored.

Of course I can use `HasCurrentTransaction`, but this feels incorrect since it is not multi-thread safe. 

I would be nice to have a `Run` method that not only passes the transaction to an action, but also a boolean indicating if a new transaction was created or not. 

Do you have any suggestions on how to replicate the behavior of `RunInitialTransaction`?

Thanks a lot,
Peter

**Comment by jam40jeff** [comment]
I looked through the history of the C# code, but I could not find a `Transaction.RunInitialTransaction` method.  What revision do you see it in?

**Comment by Ziriax** [comment]
Never mind, my bad, I actually added that method myself, but I forgot about it ;-)
